defaults:
  - arch: tts2_arch
  # - augmentations: base_augmentations
  - data: tts_dataset
  - loss: tts_loss
  - lr_scheduler: LRStep
  - metrics: base_metrics
  - preprocessing: base_preprocessing
  - trainer: base_trainer
  - optimizer: AdamW

name: base_config
n_gpu: 1
checkpoint: