_target_: tts.model.FastSpeech

coder_config:
  dropout: 0.1
  encoder_conv1d_filter_size: 1024
  decoder_dim: 256
  encoder_dim: 256
  encoder_n_layer: 4
  encoder_head: 2
  fft_conv1d_kernel: [9, 1]
  fft_conv1d_padding: [4, 0]
  vocab_size: 300



regulator_config:
  duration_predictor_filter_size: 256
  duration_predictor_kernel_size: 3
  dropout: 0.1


device: 'cuda'
max_seq_len: 3000
num_mels: 80
PAD: 0
